STATUS_OPTIONS = (
    ('PENDING', 'PENDING'),
    ('ACTIVE', 'ACTIVE'),
    ('DEACTIVATED', 'DEACTIVATED')
)

GENDER_OPTION = (
    ('MALE', 'MALE'),
    ('FEMALE', 'FEMALE')
)

TOKEN_TYPE = (
    ('ACCOUNT_VERIFICATION', 'ACCOUNT_VERIFICATION'),
    ('PASSWORD_RESET', 'PASSWORD_RESET'),
)

USER_ROLE = (
    ('SUPERADMIN', 'SUPERADMIN'),
    ('ADMIN', 'ADMIN'),
    ('CANDIDATE', 'CANDIDATE')
)
