# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\nuser_proto\x1a\x1bgoogle/protobuf/empty.proto\"g\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\x10\n\x08lastname\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12\x11\n\tis_active\x18\x08 \x01(\x08\"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x11\n\x0fUserListRequest2\xaf\x02\n\x0bUserService\x12>\n\x07GetUser\x12\x1f.user_proto.UserRetrieveRequest\x1a\x10.user_proto.User\"\x00\x12>\n\tListUsers\x12\x1b.user_proto.UserListRequest\x1a\x10.user_proto.User\"\x00\x30\x01\x12\x32\n\nCreateUser\x12\x10.user_proto.User\x1a\x10.user_proto.User\"\x00\x12\x32\n\nUpdateUser\x12\x10.user_proto.User\x1a\x10.user_proto.User\"\x00\x12\x38\n\nDeleteUser\x12\x10.user_proto.User\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=55
  _USER._serialized_end=158
  _USERRETRIEVEREQUEST._serialized_start=160
  _USERRETRIEVEREQUEST._serialized_end=193
  _USERLISTREQUEST._serialized_start=195
  _USERLISTREQUEST._serialized_end=212
  _USERSERVICE._serialized_start=215
  _USERSERVICE._serialized_end=518
# @@protoc_insertion_point(module_scope)
